name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1. Instalar todo lo necesario manualmente (A prueba de fallos)
      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev \
          ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
          libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
          zip unzip autoconf libtool pkg-config libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk

      # 2. Instalar Buildozer (La herramienta de compilación)
      - name: Instalar Buildozer y Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      # 3. Crear la APK (El comando "yes" acepta las licencias automáticamente)
      - name: Generar APK
        run: |
          yes | buildozer android debug

      # 4. Subir el resultado
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
